spring:
  # Database Configuration
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      default_schema: static_canadian_immigration_data
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Security Configuration
  security:
    filter:
      order: 10
    # OAuth2 Configuration
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            # This is the Spring Security default callback endpoint pattern
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
        # OAuth2 Provider Configuration
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000  # 24 hours in milliseconds

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api
  forward-headers-strategy: native  # Important for OAuth2 redirects

# Logging Configuration
logging:
  level:
    co.immimate: DEBUG
    co.immimate.auth.security: TRACE  # Enable detailed JWT auth logging
    co.immimate.profile.controller: DEBUG  # Enable detailed profile controller logging
    org.springframework.security: DEBUG  # Enable detailed security logging
    org.springframework.web: DEBUG  # Enable detailed web request logging
    org.hibernate: INFO
    org.springframework.security.oauth2: DEBUG  # Enable detailed OAuth2 logging

# CORS Configuration
cors:
  allowed-origins: "*"  # For development, restrict in production
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  exposed-headers: Authorization
  max-age: 3600  # 1 hour